services:

  simple_admin.crud_base_controller:
    class:     AdminBundle\Controller\CRUDBaseController
    arguments: ['@templating','@form.factory',"@doctrine.orm.default_entity_manager","@router","@session", "@security.token_storage", "@translator", "@simple_admin.filter.bag", "@security.authorization_checker", "@event_dispatcher"]
    abstract: true

  simple_admin.crud_controller:
    class:     AdminBundle\Controller\CRUDController
    parent:    simple_admin.crud_base_controller

  app.crud_controller.permission:
      parent: "simple_admin.crud_controller"
      calls:
          - [setModelType, ["AdminBundle\\Entity\\Permission"]]
          - [setFormType, ["AdminBundle\\Form\\Type\\User\\PermissionFormType"]]
          - [setHandler, ["@simple_admin.form.generic.handler"]]
          - [setRepository, ["@simple_admin.repository.permission"]]
          - [setListFields, [["id","name"]]]
          - [setSearchFields, [["a.name"]]]

  app.crud_controller.permission_group:
      parent: "simple_admin.crud_controller"
      calls:
          - [setModelType, ["AdminBundle\\Entity\\PermissionGroup"]]
          - [setFormType, ["AdminBundle\\Form\\Type\\User\\PermissionGroupFormType"]]
          - [setHandler, ["@simple_admin.form.generic.handler"]]
          - [setRepository, ["@simple_admin.repository.permission_group"]]
          - [setListFields, [["id","name"]]]
          - [setSearchFields, [["a.name"]]]